### ISSUE TITLE
Issues with words "ovan" and "pas"

### ISSUE THREAD

**Issue by juricb** [krunose/hr-hunspell#1]
Hello,

Word _ovan_ is in the dictionary, but there is no rule assigned. In fact there is no appropriate rule for this word.

For word _pas_ as an animal there is an entry _pas/265_ but that rule seems to be incorrect because there are no forms for _psa, psi, pse, psima,..._

**Comment by krunose** [comment]
Hi, juricb

and thank you for this report.

I looked into it and here's the summary:

Words can be added do dictionary or as list of words placing any form of a word right below previous one:

<pre>
ovan
ovna
ovnu
[...]
pas
psa
psu
[...]
</pre>

or just one form of a word could be placed in dictionary file and then class from affix file can be applied to it:

<pre>
pas/265
</pre>

as affix file handles rest of the forms.

From users' perspective, there is no difference between approaches. Both work well and both are legit.

If you search trough dictionary file, you'll see that all forms of word 'ovan' are contained there (first approach used).

Same goes for word 'pas' (eng. dog). Now, entry 'pas/265' is different word and it's pronounced 'pâs' and correspond to English word 'waist': pȁs ~ pâs.

I know not all words have affix rules assigned but that doesn't affect user in any way so I put that aside for now.

Adding new affix classes is hard and I plan to do rewrite of the whole thing for version 3.0 (by the end of the spring).

For now, I'm adding new words to the dictionary and making sure that wanted correction does not come last in suggestion list. There's still a lot to add to the dictionary but also to exclude from it. Think that should have priority.

I'm very happy for even having such rich affix file as it happened only this year in version 2.0 (see `izmjene-u-rjecniku.md` for more information).

Rewriting of affix file would make dictionary much more modular so fixing this kind of glitches in the future should not be hard and I will make adding new words and maintaining the dictionary a whole lot easier.

To put long story short: I'm aware of this issues but they are not hurting users and instead patching it in the fly, I'm planning to deal with it the right way which takes time.

You can make new suffix rule for 'ovan' and 'pas' and I'll be happy to add your patch.

Kruno

**Comment by juricb** [comment]
Hi Kruno,

Thank you for an explanation.
At this point I don't have enough experience  to be able to create a new rule that would fit these word examples.
I'm definitely looking forward to now, rewritten rules in 3.0

Do you assign rules to words manually or do you have an automation to help you with that?

Boris

**Comment by krunose** [comment]
> Do you assign rules to words manually or do you have an automation to help you with that?

Well, I do it by hand for now. For computer script to be accurate, words in dictionary file should be tagged (by hand) so script could assign rules from affix file.

It's not hard to assign rule to a new word but it's hard to remember all the affix names so I first need to check what rule to apply (read trough affix file) and then assign affix class name to a new word.

I do have a spreadsheet table (made by Mirko K. [see [README_hr_HR.txt](https://github.com/krunose/hr-hunspell/blob/master/README_hr_HR.txt)) so I can make a quick check if rule I'm looking at actually fit for the word that needs to be added.

That spreadsheet table (LibreOffice Calc) is one more reason why I don't hurry with altering affixes as I need to make a new spreadsheet file or a script to check all forms that particular rule would generate.

What I plan to do is keep words in a separate file and tag every word with something meaningful to humans read and write to speed up the process: pas/265 is not very descriptive but

<pre>
pas IM:mr:jm:km:na
</pre>

might not make much sense at first but it describes that particular word very well.

- IM → noun
- mr → muški rod (male [gender])
- jm → jednina i množina (singular and plural [as some words have only singular or only plural])
- km → kratka množina (short form in plural [pas → psi ~ vitez → vitez**ov**i
- na → nepostojano a (a is not present in every case: pas ~ psa

Now script can take tag `IM:mr:jm:km:na` and read trough affix file and pull needed affix file and then save change to a dictionary file.

I would not recommend automating this process in any other way as errors would be inevitable. In a too much cases you can't tell which affix to apply just by just looking how word looks. Consider your example `pas` as 'dog' and `pas` as waist. They look the same but there are grammatical differences:

<pre>
dog:

pas
psa
[...]
psi
psima
</pre>

against

<pre>
waist:

pas
pasa
[...]
pasovi
pasovima
</pre>

and some word on -ski which can be adjectives and adverbs "at the same time". This approach is base for using Hunspell as morphological analyzer for Croatian.

Such tagged words would also be very useful for making grammar checker using [LanguageTool](https://www.languagetool.org/) as it would be possible to write more complex and robust rules.

You can e-mail me and I will send you the spreadsheet table so you can check words or affix rules you're interested in. Dictionary could benefit from new pair of eyes.

Just be aware that affix rules are not very modular at the moment. In some occasions 'fixing' one affix rule means breaking things for other set of words with that particular affix rule.

For the end: yes, I do everything on hands for now, with exception of using sed, grep and such for searching trough dictionary and affix file.

**Comment by juricb** [comment]
Interesting approach, I see how that spreadsheet is very helpful. I will e-mail you about it. Next week I will be looking into some words, so I can return some feedback if I find mistaken rules.

I'll try to explain now an approach that would partly automate assigning rules to new words.

First you need a big collection of texts in Croatian.  Preferably editorial content from newspapers and/or books that passed proofreading and manual corrections.
You index all the words from that text collection in their original form, without any stemming.

Then you need a script that would take a word input (for a new word you want to add to a dictionary) and rule by rule, apply all the rules from the dictionary to that word to create all the possible and impossible word forms using all the rules.
Then it uses all the created word variations, one by one, to search our huge text collection index.
If a word is found, then it's possible word form that _appears in the wild_, and if it isn't, then it's most likely wrong word form.

As a result, you can rate how good of a match any dictionary rule is to any word.

Our goal is to identify rules that are best matches for our word. It can suggest several rules that are most likely to be correct, and then you just approve one of them manually.
That would reduce your choice for any new word from 400 to only several rules.

What do you think of it?
Unfortunately I don't have sills or knowledge to create it.
I would be surprised if such a tool does not exist for some other languages.

Boris

**Comment by krunose** [comment]
Thank you for suggestion I'll see what I can do about it.

I'm not a programmer just a tinkerer and might be a bold statement but I might be able to make such script. It would take some effort and what's bugging me is that we don't have corpora to work with. Scrapping just Wkipedia is not a good idea as there's not much proofreading going on and it's only one type of text. Wikipedia contains to much specialized words not used often as it tend to be more scientific. I like your idea very much but I'm not sure we can pull this off.

Words in dictionary files are good, it's good balance and I have over five hundred words pending to be added to dictionary right now. I would like you to help me with that when I send you that spreadsheet as this is priority. Regular users would benefit more from new words then reconfiguring affix file which already works as Mirko K. did a really great job with that. Yes, there's room for improvement but in a sense of simplifying and systematizing affixes but that should be done slowly, systematic and the smart way, no rush.

Back to automation: computer scripts tend to make understanding of underling system hard for humans. What I want to do is make rules identical how Croatian is described in grammar books as this is intuitive and well 'documented' so anybody can participate as this system is taught at school. Tagging system seams easier to me as we don't have corpora. Linguists already described the language very well so I don't think that confirming rules is necessary, all we need to do is transform rules from grammar books to rules Hunspell understands.

Rules should be doing only cases not word formations and/or derivational morphology. We can discuss this privately over mail. Think that we could reduce significantly number of rules doing it this way.

Would you like me to upload list of words that I collected to be added do dictionary so you can check them out?

**Comment by krunose** [comment]
I've made two new affix classes and applied them to 'pas' and 'ovan' respectively so I'm considering this issue fixed.

Feel free to open a new issue when you find something wrong.
