### ISSUE TITLE
Typo in .dic file?

### ISSUE THREAD

**Issue by igzivkov** [krunose/hr-hunspell#2]
Elasticsearch throws an error on loading the dictionary:

```
[ERROR][o.e.i.a.HunspellService  ] [azYCX94] Could not load hunspell dictionary [hr_HR]
java.lang.NumberFormatException: For input string: "205i"
```
In hr_HR.dic at line 11963 there is the entry:

`iglun/205i`

**Comment by krunose** [comment]
Yes, it's a typo. Was away for three days and just saw somebody already merged fix for LibreOffice. I update fix in this GitHub repository too.

Hunspell from command line is not giving me any errors or warnings. Wondering should that be reported to Hunspell also?

Thanks for reporting this.

**Comment by krunose** [comment]
Could you please report me back if Elasticsearch still throws error about this? I would like to close this issue if it's fixed to keep bug tracker neat and clean.

**Comment by igzivkov** [comment]
Sorry, forgot to mention that it works fine with that "i" character removed.

**Comment by spideyfusion** [comment]
I can also confirm that this resolves the issue. Thanks a lot!

**Comment by krunose** [comment]
So I'm closing this. Reported this to Hunspell also as warning from Hunspell could help me prevent this from happening in the future.

Thanks
